
[target.x86_64-unknown-linux-gnu]
rustflags = ["-Ctarget-cpu=x86-64-v3"]

[target.x86_64-pc-windows-msvc]
rustflags = ["-Ctarget-cpu=x86-64-v3"]

[target.x86_64-pc-windows-gnu]
rustflags = ["-Ctarget-cpu=x86-64-v3"]

[target.x86_64-apple-darwin]
rustflags = ["-Ctarget-cpu=x86-64-v3"]
