on: [push, pull_request]

name: build

env:
  CARGO_TERM_COLOR: always
  LLVM_SYS_180_PREFIX: ${{ github.workspace }}/llvm

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      
      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true

      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v4
        with:
          path: |
            C:/Program Files/LLVM
            ./llvm
          key: llvm-18

      - name: Cache Cargo registry
        id: cache-cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Install LLVM and Clang
        uses: purpl3F0x/install-llvm-action@rebuild-dist
        with:
          version: "18"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}

      - name: Install libncurses5
        if: runner.os == 'Linux'
        run: sudo apt update && sudo apt install -y libncurses5
      - name: llvm-config
        run: llvm-config --version --bindir --libdir

      # `cargo check` command here will use installed `nightly`
      # as it is set as an "override" for current directory
      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --release

      - name: Test
        uses: actions-rs/cargo@v1
        continue-on-error: true
        with:
          command: test
          args: --all --release

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --all-features

      - name: Archive binary
        uses: actions/upload-artifact@v4
        with:
          name: alanc-dist
          path: |
            target/release/alanc
            target/release/libalan.a
